version: '3.8'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Username=postgres;Password=admin;Database=mtcg;Pooling=true;MinPoolSize=10;MaxPoolSize=100;   
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mtcg
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - type: bind
        source: ./Server/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: