services:
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=admin;Database=mtcg
  db:
    image: postgres:15
    container_name: mtcg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mtcg
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #volumes:
    #db_data:
